### ISSUE TITLE
Incorrect SVN URL in quiz3.md

### ISSUE THREAD

**Issue by ambyjkl** [patricklam/se101-f16#11]
Dear Sir
The correct URL is https://ecesvn.uwaterloo.ca/courses/se101/2016/students/YOUR_WATID/
Not https://ecesvn.uwaterloo.ca/courses/se101/students/YOUR_WATID/
Notice the lack of the year 2016
Regards
Ambareesh Balaji

**Comment by rollends** [comment]
I've also uploaded the corrected version on Learn, Thanks!
